#!/bin/bash

echo "🏋️‍♂️ Yousef Recharge - Live Deployment Setup"
echo "============================================="

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "📦 Installing Railway CLI..."
    npm install -g @railway/cli
fi

echo "🔑 Please log in to Railway..."
railway login

echo "🚀 Creating new Railway project..."
railway new yousef-recharge-fitness

echo "🗄️ Adding PostgreSQL database..."
railway add postgresql

echo "⚙️ Setting up environment variables..."

# Generate JWT secret
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")

railway variables set NODE_ENV=production
railway variables set JWT_SECRET="$JWT_SECRET"
railway variables set PORT=8080

echo "🔧 Environment variables set:"
echo "   ✅ NODE_ENV=production"
echo "   ✅ JWT_SECRET=(generated)"
echo "   ✅ PORT=8080"
echo "   ✅ DATABASE_URL=(auto-generated by Railway)"

echo ""
echo "📋 Next steps:"
echo "1. Add your API keys (optional):"
echo "   railway variables set STRIPE_SECRET_KEY=sk_test_..."
echo "   railway variables set TWILIO_ACCOUNT_SID=AC..."
echo "   railway variables set TWILIO_AUTH_TOKEN=..."
echo ""
echo "2. Deploy your app:"
echo "   git add ."
echo "   git commit -m 'Deploy live fitness platform'"
echo "   railway up"
echo ""
echo "3. Get your live URL:"
echo "   railway status"
echo ""
echo "🎯 Your fitness platform will be live with:"
echo "   ✅ PostgreSQL database"
echo "   ✅ User registration/login"
echo "   ✅ Workout tracking"
echo "   ✅ Meal planning"
echo "   ✅ Progress analytics"
echo "   ✅ Subscription management"

read -p "Press Enter to continue with deployment..."

echo "🚀 Deploying to Railway..."
git add .
git commit -m "Deploy live fitness platform with real database"
railway up

echo ""
echo "🎉 Deployment complete!"
echo "Getting your live URL..."
railway status
